### ISSUE TITLE
attempted to send message of length 33 on uninitialized socket spam

### ISSUE THREAD

**Issue by cjsthompson** [haavardp/tox-weechat#22]
When connecting with tox, the profile window is spammed every 10 seconds with about 20 times the following message:

tox | network.c:484 [sendpacket] attempted to send message of length 33 on uninitialized socket

Note that I'm connecting with SOCKS5/tor (udp set to off). Connection seems to work, contacts appear. Weechat process is firejail'ed.

**Comment by nogaems** [comment]
Hi, @cjsthompson 
Since you're able to use Tox, as a workaround I'd suggest you to just basically disable these messages choosing `Release` build type by adding `-DCMAKE_BUILD_TYPE=Release` to the `cmake` command.
I'm experiencing the same issue with the only difference that I can't get connected to Tox at all with UDP option being turned off, and I'm getting exactly the same messages.
Currently I'm trying to address this and I've asked some people to reproduce this problem. The outcome vary from environment, OS, etc. And the fact is that only about a half of people were able to run Tox without UDP. 
The code accountable for this issue initially appears here https://github.com/TokTok/c-toxcore/commit/21675ce0d2581597b0e0a727ab4cf6cfb796a037 and its commit message is pretty describing. I've even asked the devs on IRC if it's a well-known issue I'm dealing with, they say Tox *should* work fine without UDP, otherwise I got to raise an issue. But I also found this issue report https://github.com/qTox/qTox/issues/5426 which means that this is definitely not a problem with ToxWeeChat plugin. And it's 4 months passed, but it's still open without any meaningful response.
Anyway, I'll hit you up here if I know something more. I'm going to spend some time with gdb and figure it out closely.

**Comment by cjsthompson** [comment]
Thanks for the tip. I'm going to rebuild with the Release build type.

I've been using toxic also with tor for years now with no problem, and some times qTox without tor and haven't had any problems with those. But toxic doesn't have a firejail profile. So I thought that might be the difference.

EDIT: No more spam with "Release" and still seems to be working. Thanks!

**Comment by haavard** [comment]
Thanks for the useful and detailed response, @nogaems!
